services:
  server-web:
    image: some-image.dev.nvim                  # dev-image
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile.dev.nvim  # dev-image
    ports:
      - 80:80
      - 443:443
    volumes:
        # Nvim DATA and STATE directories (SHADA-Files, harpoon.json, etc.)
      - type: bind 
        source: ./../.steven/nvim/XDG_STATE_HOME
        target: /root/.local/state/nvim
      - type: bind 
        source: ./../.steven/nvim/XDG_DATA_HOME
        target: /root/.local/share/nvim
